### ISSUE TITLE
fix: 기능 디테일 수정

### ISSUE THREAD

**Issue by ingssg** [hongal-dan/egg-signal-app#115]
# Issues

기능적으로 부족한 부분 수정하겠습니다.

# Todos

- [x] 메인화면 캠 on/off 만들기
- [x] 미팅 종료 후 매칭 여부에 따른 친구 버튼 유/무
- [x] 친구 요청 1회 보내면 친구 요청 버튼 차단
