### ISSUE TITLE
feat: 화상채팅 페이지 합치기

### ISSUE THREAD

**Issue by ingssg** [hongal-dan/egg-signal-app#13]
# New Features

따로 작업한 화상채팅 페이지 기능들 메인 브랜치랑 합치기

# Todos

- [x] ui변경 함수 추가
- [x] 흑백 전환 함수 추가
- [x] 사랑의 작대기 함수 추가
- [x] 캠 오픈 함수 추가
- [x] 랜덤 키워드 띄우는 ui + 함수 추가
- [x] mindar로 캠에 ar 씌우기
- [x] 서버랑 소켓 통신해서 openvidu 연결
- [x] 사람 선택 모드 함수 추가
- [x] 메인페이지에서 입장 버튼 클릭 시 로딩 이후 화상채팅 페이지로 이동

# References
- Related Issue: #6 
- [서버 레포](https://github.com/hongal-dan/egg-signal-server)
