### ISSUE TITLE
fix: 룰렛 확실히 보이게 하기

### ISSUE THREAD

**Issue by ingssg** [hongal-dan/egg-signal-app#146]
# Issues

룰렛 눈에 잘 띄게 보이게 하기

# Todos

- [x] 룰렛 순서 나, 0, 1, 4, 3, 2 순서로 변경
- [x] 룰렛 시간 증가
- [x] 룰렛 표시 확실히
- [x] 룰렛 타임 때 배경 어둡게
