### ISSUE TITLE
feat: 친구목록, 채팅 UI 추가 작업 및 채팅/알람 common 소켓 연결

### ISSUE THREAD

**Issue by hyeong1** [hongal-dan/egg-signal-app#18]
# New Features

1. feat 친구목록, 채팅 UI 추가 작업 및 채팅 common 소켓 연결

# Todos

- [ ] 친구목록 -친구 닉네임, 온라인 여부 표시
- [ ] 채팅 -채팅 중인 상대방 닉네임+온라인 여부 표시, 채팅 내역, 채팅 input 창
- [ ] 채팅 서버 common 소켓 연결
- [ ] 채팅 데이터 송수신 확인

# References
- Related Issue: #
- link1
