### ISSUE TITLE
feat: ar 최적화

### ISSUE THREAD

**Issue by ingssg** [hongal-dan/egg-signal-app#22]
# New Features

1. 아바타 선택 타이밍 변경
2. 아바타 최적화

# Todos

- [x] 미팅 페이지에서 아바타 선택하도록 하기
- [x] 캠 오픈 시간에 ar 완전 제거
- [x] 아바타 렌더링 하면서 이전 데이터 제거
- [x] 메모리 누수 잡기
