### ISSUE TITLE
feat: 채팅 알람 기능

### ISSUE THREAD

**Issue by hyeong1** [hongal-dan/egg-signal-app#26]
# New Features

1. feat 채팅 알람 기능

# Todos

- [x] 채팅 알람 소켓 이벤트 연결
- [x] 채팅 알람 UI 표시
- [ ] 채팅 읽으면 알람 UI 제거하기

# References
- Related Issue: #
- link1
