### ISSUE TITLE
feat: 사생대회

### ISSUE THREAD

**Issue by won-N-only** [hongal-dan/egg-signal-app#28]
# New Features

1. 유저에게 그림 그릴 수 있는 환경 제공
2. 마음에 드는 그림을 투표
3. 1등에게 1:1대화 선택권 

# Todos

- [x] 기작성 코드 egg-signal-app으로 이전
- [x] event 'drawingContest'오면 유저에게 그림 그릴 수 있는 canvas 띄우기
- [x] 유저가 submit한 그림 emit
- [x] 서버에서 온 그림 배열 유저에게 주기 on
- [x] 유저에게 투표창 띄우기
- [x] 유저의 닉네임과 선택한 그림을 그린 사람 emit
- [x] 서버에서 온 winner 유저에게 주기 on
- [x] winner에게 선택창 띄우기
- [x] [winner, winner가 선택한 사람], [lossers] emit
- [x] 유저 위로 모달 띄우기
- [ ] winner 1:1 대화로 화면 이동
- [ ] 이벤트 타이머 
- [ ] ui다듬기

# References
- [백엔드 사생대회](https://github.com/hongal-dan/egg-signal-server/issues/58)

# Note
- 브랜치 꼬여서 egg-signal-app-41로 재작업
