### ISSUE TITLE
feat: 사생대회 UI/UX

### ISSUE THREAD

**Issue by won-N-only** [hongal-dan/egg-signal-app#47]
# New Features

1. 사생대회 화면 UI / UX 
2. winners[] 1:1 대화 연결

# Todos

- [x] 사생대회 전체 UI
- [x] 투표시 선택항목 알 수 있게 하기
- [x] 캔버스 떴을때 스크롤 없애기
- [x] 우승자의 투표 화면에 나머지 사람들 얼굴 캡처 넣기
- [x] 그림, 투표 때 타이머 넣기
- [x] winners[] 공개 후 모달 꺼지게 하기
- [ ] 그림그리기 이후 ui
- [ ] winners[] 1:1 대화

# References
- Related Issue: #28
