### ISSUE TITLE
feat: 캠 오픈 이전 송출 비디오 변경

### ISSUE THREAD

**Issue by ingssg** [hongal-dan/egg-signal-app#48]
# New Features

캠 오픈 이전 송출 비디오 변경

# Todos

- [x] 캔버스에 비디오 송출
- [x] 캔버스 위에 ar 적용
- [x] 캡쳐 후 openVidu에 전송
