### ISSUE TITLE
feat: 메인페이지 만들기

### ISSUE THREAD

**Issue by hyeong1** [hongal-dan/egg-signal-app#5]
# New Features

1. feat5 메인페이지 만들기

# Todos

- [x] tailwind css 적용하기
- [x] 로그인, 회원가입 폼 formik로 만들기
- [x] 메인페이지 틀 만들기 (기본 입장/친구/알림 ui)
- [x] 메인페이지에 카메라, AR 캐릭터, AR 캐릭터 on/off 구현 

# References
- Related Issue: #
- [egg-signal 피그마 링크](https://www.figma.com/design/TIsFHSSYdBKoeleq3CO3y1/Untitled?node-id=0-1&m=dev)
