### ISSUE TITLE
fix: jwt 토큰 쿠키 -> 헤더

### ISSUE THREAD

**Issue by ingssg** [hongal-dan/egg-signal-app#59]
# Issues
jwt 토큰 쿠키 -> 헤더

# Todos

- [x] 토큰 로컬스토리지에 저장
- [x] rest api 리퀘스트 헤더에 토큰 담기
- [x] websocket 연결시 auth에 토큰 담기

# References
- (https://github.com/hongal-dan/egg-signal-server/pull/96)
