### ISSUE TITLE
feat: mindar AR 캐릭터 출력 구조 파악하기

### ISSUE THREAD

**Issue by sh940701** [hongal-dan/egg-signal-app#7]
# 문제 상황 
mindar 라이브러리를 사용하니까 비디오 크기 변경 및 레이어 겹침 현상 등
6인 화상채팅 프로젝트에 적용하기엔 제약이 많다고 생각하여 직접 구현의 필요성을 느낌

# New Features
AR 캐릭터 출력 구조 파악 후 mindar 라이브러리 사용 안하고 직접 구현

# Todos

- [x] mindar 라이브러리 사용한 코드 분석
- [ ] 라이브러리 내부 코드 분석
- [ ] 라이브러리 사용 없이 직접 구현

# References
#4
