### ISSUE TITLE
fix: 선택 차단

### ISSUE THREAD

**Issue by ingssg** [hongal-dan/egg-signal-app#76]
# Issues

선택 차단

# Todos

- [ ] 동성 선택 차단
- [ ] 본인 선택 차단
- [ ] 중복 선택 차단
