### ISSUE TITLE
feat: 로그인/회원가입 API 연결

### ISSUE THREAD

**Issue by hyeong1** [hongal-dan/egg-signal-app#9]
# New Features

1. feat9 로그인/회원가입 API 연결하기

# Todos

- [x] axios 패키지 설치
- [x] API service 파일 분리해서 만들기
- [x] 회원가입 api 연결 +성별 입력칸 추가하기
- [x] 로그인 api 연결 
- [x] 회원가입/로그인 후 페이지 이동 구현

# References
- Related Issue: #
- [Next js with Axios Data Fetching](https://dev.to/syedmuhammadaliraza/next-js-with-axios-data-fetching-435a)
- [Next.js 폴더/파일 구조 잡기](https://miriya.net/blog/cliz752zc000lwb86y5gtxstu)
