### ISSUE TITLE
feat: 미팅 중 이모티콘 전송

### ISSUE THREAD

**Issue by won-N-only** [hongal-dan/egg-signal-app#92]
# New Features

1. 미팅 중 이모티콘을 전송 할 수 있는 기능

# Todos

- [ ] 이모지을 담고 있는 컴포넌트 추가
- [ ] 이모지 onClick으로 서버에 emit (nickname, emoji)
- [ ] 서버가 준 이모지 정보 받기
- [ ] 이모지를 유저 비디오 좌측상단에 띄우기 
- [ ] 이모지의 지속시간 설정 

# References
- Related Issue: #
- link1
